// Code generated by pg-bindings generator. DO NOT EDIT.
package n35ton36

import (
	"context"

	"github.com/jackc/pgx/v4/pgxpool"
	"github.com/pkg/errors"
	"github.com/stackrox/rox/generated/storage"
	"github.com/stackrox/rox/migrator/migrations"
	"github.com/stackrox/rox/migrator/migrations/loghelper"
	legacy "github.com/stackrox/rox/migrator/migrations/n_35_to_n_36_postgres_node_cves/legacy"
	pgStore "github.com/stackrox/rox/migrator/migrations/n_35_to_n_36_postgres_node_cves/postgres"
	"github.com/stackrox/rox/migrator/types"
	pkgMigrations "github.com/stackrox/rox/pkg/migrations"
	pkgSchema "github.com/stackrox/rox/pkg/postgres/schema"
	"github.com/stackrox/rox/pkg/rocksdb"
	"github.com/stackrox/rox/pkg/sac"
	"gorm.io/gorm"
)

var (
	migration = types.Migration{
		StartingSeqNum: pkgMigrations.CurrentDBVersionSeqNum() + 35,
		VersionAfter:   storage.Version{SeqNum: int32(pkgMigrations.CurrentDBVersionSeqNum()) + 36},
		Run: func(databases *types.Databases) error {
			legacyStore, err := legacy.New(databases.PkgRocksDB)
			if err != nil {
				return err
			}
			if err := move(databases.PkgRocksDB, databases.GormDB, databases.PostgresDB, legacyStore); err != nil {
				return errors.Wrap(err,
					"moving node_cves from rocksdb to postgres")
			}
			return nil
		},
	}
	batchSize = 10000
	schema    = pkgSchema.NodeCvesSchema
	log       = loghelper.LogWrapper{}
)

func move(legacyDB *rocksdb.RocksDB, gormDB *gorm.DB, postgresDB *pgxpool.Pool, legacyStore legacy.Store) error {
	ctx := sac.WithAllAccess(context.Background())
	store := pgStore.New(postgresDB)
	pkgSchema.ApplySchemaForTable(context.Background(), gormDB, schema.Table)
	var nodeCves []*storage.NodeCVE
	var err error
	legacyStore.Walk(ctx, func(obj *storage.NodeCVE) error {
		nodeCves = append(nodeCves, obj)
		if len(nodeCves) == 10*batchSize {
			if err := store.UpsertMany(ctx, nodeCves); err != nil {
				log.WriteToStderrf("failed to persist node_cves to store %v", err)
				return err
			}
			nodeCves = nodeCves[:0]
		}
		return nil
	})
	if len(nodeCves) > 0 {
		if err = store.UpsertMany(ctx, nodeCves); err != nil {
			log.WriteToStderrf("failed to persist node_cves to store %v", err)
			return err
		}
	}
	return nil
}

func init() {
	migrations.MustRegisterMigration(migration)
}
